Conditionally use sk_use_task_frag
Fixes compile error introduced with upstream commit 98123866fcf3
("Treewide: Stop corrupting socket's task_frag"):

    usbip_common.c:318:11: error: ‘struct sock’ has no member named ‘sk_use_task_frag’
    318 |   sock->sk->sk_use_task_frag = false;
        |           ^~