Backport: vudc: Conditionally use remove_new callback
Fixes compile error introduced with upstream commit b9a24821c7f7 ("USB: usbip:
vudc: Convert to platform remove callback returning void"):

    vudc_main.c:22:3: error: ‘struct platform_driver’ has no member named ‘remove_new’; did you mean ‘remove’?
    22 |  .remove_new = vudc_remove,
       |   ^~~~~~~~~~
       |   remove