Backport: Add USBIP_URB_* URB transfer flags
Copy defines, that were added in include/uapi/linux/usbip.h.

Fixes compile error introduced with upstream commit 8f36b3b4e1b5
("usbip: add USBIP_URB_* URB transfer flags"):

    usbip_common.c:388:21: error: ‘USBIP_URB_SHORT_NOT_OK’ undeclared here (not in a function); did you mean ‘URB_SHORT_NOT_OK’?
    388 |  {URB_SHORT_NOT_OK, USBIP_URB_SHORT_NOT_OK},
        |                     ^~~~~~~~~~~~~~~~~~~~~~
        |                     URB_SHORT_NOT_OK