Backport: Conditionally use old driver member name
Fixes compile error introduced with upstream commit 49a78b05d5ca ("USB: core:
Use device_driver directly in struct usb_driver and usb_device_driver"):

    stub_main.c:380:39: error: ‘struct usb_device_driver’ has no member named ‘driver’
    380 |  ret = driver_create_file(&stub_driver.driver,