Conditionally define kthread_stop_put
The kthread_stop_put definition was moved to linux/kthread.h. Define it
again for older Kernel versions.

Fixes compile error introduced with upstream commit 6309727ef271
("kthread: add kthread_stop_put"):

    vhci_sysfs.c:403:3: error: implicit declaration of function ‘kthread_stop_put’; did you mean ‘kthread_stop’? [-Werror=implicit-function-declaration]
    403 |   kthread_stop_put(tcp_rx);
        |   ^~~~~~~~~~~~~~~~
        |   kthread_stop