vhci_hcd: Conditionally use remove_new callback
Fixes compile error introduced with upstream commit 19b3cf44e18c
("usbip: vhci_hcd: Convert to platform remove callback returning void"):

    vhci_hcd.c:1486:3: error: ‘struct platform_driver’ has no member named ‘remove_new’; did you mean ‘remove’?
    1486 |  .remove_new = vhci_hcd_remove,
         |   ^~~~~~~~~~
         |   remove

Also handles commit 9a0749d61a9a ("usb: Switch back to struct
platform_driver::remove()")