Conditionally define str_plural()
str_plural() was added in upstream commit 9ca5facd0400
("lib/string_choices: Add str_plural() helper"). Define it for older
Kernels.

Fixes compile error introduced with upstream commit f386bfad038d ("USB:
Use str_enable_disable-like helpers"):

    vhci_hcd.c:14:10: fatal error: linux/string_choices.h: No such file or directory
       14 | #include <linux/string_choices.h>
          |          ^~~~~~~~~~~~~~~~~~~~~~~~