iov_iter direction initializer new names
Fixes compile error introduced with upstream commit de4eda9de2d9 ("use
less confusing names for iov_iter direction initializers"):

    usbip_common.c:312:31: error: ‘ITER_DEST’ undeclared (first use in this function)
    312 |  iov_iter_kvec(&msg.msg_iter, ITER_DEST, &iov, 1, size);
        |                               ^~~~~~~~~